# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftTestProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftTestProject
pod 'IQKeyboardManager'
pod 'IISI_SwiftLib'
end

target 'SwiftTestProjectUITests' do
  use_frameworks!
pod 'KIF'
pod 'Nimble'
end